{% set name = "fast_dp" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower|replace("-", "_") }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9c6ea98d3a352ae391166a616cc5451a32f3bf8cc434aafedaf641edd5ef978
  patches:
    - procrunner.diff

build:
  noarch: python
  number: 0
  entry_points:
    - fast_dp = fast_dp.fast_dp:main
    - fast_rdp = fast_dp.fast_rdp:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dxtbx

test:
  imports:
    - fast_dp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DiamondLightSource/fast_dp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Fast DP: Fast Data Processsing with XDS'
  description: |
    Fast DP is a small Python program which uses XDS, CCP4 & CCTBX
    to very quickly deliver data processing results for single-crystal
    X-ray crystallography experiments.
    Please note that you need to install XDS, CCP4, and CCTBX manually
    as they are not available as conda-forge packages.
  doc_url: https://github.com/DiamondLightSource/fast_dp#fast-dp-fast-data-processsing-with-xds
  dev_url: https://github.com/DiamondLightSource/fast_dp

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - Anthchirp
